import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Canvas} from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';
import Keyboard from '@/components/Keyboard';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.canvasWrap}>
          <Canvas camera={{ manual: true }}>
            <ambientLight intensity={0.2} />
            <directionalLight color="white" position={[-1, 1, -1]} intensity={5} />

            <Keyboard scale={0.1} />

            <OrbitControls />
          </Canvas>
        </div>
      </main>
    </>
  )
}
