import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Canvas} from '@react-three/fiber';
import { OrbitControls, OrthographicCamera, Plane, Stats } from '@react-three/drei';
import Keyboard from '@/components/Keyboard';
import { MeshLambertMaterial } from 'three';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const planeMaterial = new MeshLambertMaterial({ color: "#ff0000" });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.canvasWrap}>
          <Canvas shadows="basic">

            <ambientLight intensity={0.2} />
            <pointLight 
              intensity={3} 
              position={[10, 100, 10]} 
              color="white"
              castShadow
            />

            <Plane 
              scale={290} 
              material={planeMaterial} 
              rotation-x={(-Math.PI / 2)}
              position={[0, -7, 0]}
              receiveShadow
            />
            <Keyboard scale={0.08} position={[0, 0, 0]} castShadow />

            <OrthographicCamera
              makeDefault
              zoom={8}
              near={1}
              far={220}
              position={[-50, 40, 50]}
              rotation-x={(-Math.PI / 4)} 
              rotation-y={(-Math.PI / 4)} 
              rotation-z={(-Math.PI / 5)}
            />


            {/* <OrbitControls /> */}
            {/* <Stats /> */}
          </Canvas>
        </div>
      </main>
    </>
  )
}
